_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 71
                - 98
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 71
                - 98
            "3":
                - 13
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.0
            "6": 4.46.3
            "8":
                - 3
                - 5
            "12": 0.19.0
            "13": windows-amd64
